name: Build Bugs package and create release

on:
  push:
    tags: ["*"]


jobs:
  build-and-release:
    strategy:
      matrix:
        go-version: ['stable']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Get os name
        id: get-name
        shell: bash
        run: |
          OS=${{ matrix.os }}
          echo "os=${OS%-*}" >> "$GITHUB_OUTPUT"

      - name: Build
        run: |
          go build -o bugs-${{ steps.get-name.outputs.os }}-${{ github.ref_name }} cmd/bugs/main.go

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: bugs-${{ steps.get-name.outputs.os }}-${{ github.ref_name }}
