name: Test Code and with test coverage report

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - README.md
      - .github*
      - .gitignore


jobs:
  test:
    strategy:
      matrix:
        go-version: ['stable']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test the code
        run: go test
